name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions: write-all

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker build
        run: |
          docker build -t ghcr.io/vladimir-tl/loan-app/loan-app:latest .

      - name: Docker push
        run: |
          docker push ghcr.io/vladimir-tl/loan-app/loan-app:latest
